# Generated by Django 4.0.4 on 2022-08-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Please enter a title..', max_length=60)),
                ('summary', models.CharField(default='Please enter a summary..', max_length=90)),
                ('gist', models.CharField(default='Please enter a gist..', max_length=250)),
                ('problem', models.CharField(default='Please enter a problem..', max_length=250)),
                ('content', models.TextField(default='Please enter a content..', max_length=10000)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(default='default', editable=False, max_length=50)),
                ('score', models.IntegerField(default=0, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Please enter your fullname..', max_length=30)),
                ('lastname', models.CharField(default='Please enter your fullname..', max_length=30)),
                ('username', models.CharField(default='Please enter your username..', max_length=30, unique=True)),
                ('email', models.EmailField(default='Please enter your email address..', max_length=60)),
                ('age', models.IntegerField(default=18)),
                ('introduction', models.CharField(default='Please enter your introduction..', max_length=1000)),
                ('academic_history', models.CharField(default='Please enter yourademic history..', max_length=1000)),
                ('qualifications', models.CharField(default='Please enter your qualifications..', max_length=1000)),
                ('job', models.CharField(default='Please enter your job..', max_length=250)),
            ],
        ),
    ]
